name: Deploy to Cloud Server

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      deployMessage:
        description: 'Deployment message'
        required: true
        default: 'Manual deployment triggered'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image	#打包镜像
        run: |
          docker build -t vino2snax/note:${{ github.sha }} .
          docker tag vino2snax/note:${{ github.sha }} vino2snax/note:latest

      - name: Login to Docker Hub	#登录Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub	#推送到Docker Hub
        run: |
          docker push vino2snax/note:latest
          docker push vino2snax/note:${{ github.sha }}

      - name: Deploy to server	#部署到服务器
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull vino2snax/note:${{ github.sha }}
            docker stop note || true  
            docker rm note || true   
            docker run -d --name note -p 9003:9003 vino2snax/note:${{ github.sha }}